export const SWITCH_ROUTE = "SWITCH_ROUTE";
export const REQRES_USERS_FETCHED = "REQRES_USERS_FETCHED";
export const REQRES_USERS_CLEARED = "REQRES_USERS_CLEARED";
export const TOURS_TWITCHED = "TOURS_TWITCHED";
export const TOURS_EMPTY = "TOURS_EMPTY";
export const SWITCH_REVIEWER = "SWITCH_REVIEWER";
export const SHOW_ALL = "SHOW_ALL";
export const BREAKFAST_REMAINED = "BREAKFAST_REMAINED";
export const LUNCH_REMAINED = "LUNCH_REMAINED";
export const SHAKES_REMAINED = "SHAKES_REMAINED";

