export const SWITCH_ROUTE = "SWITCH_ROUTE";
export const REQRES_USERS_FETCHED = "REQRES_USERS_FETCHED";
export const REQRES_USERS_CLEARED = "REQRES_USERS_CLEARED";
export const TOURS_TWITCHED = "TOURS_TWITCHED";
export const TOURS_EMPTY = "TOURS_EMPTY";
export const SWITCH_REVIEWER = "SWITCH_REVIEWER";
